name: crm_application
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.4
  provider: ^6.0.2
  shared_preferences: ^2.0.13
  fluttertoast: ^8.0.8
  google_fonts: ^2.3.1
  flutter_screenutil: ^5.3.1
  #firebase_messaging: ^11.2.6
  firebase_messaging: ^10.0.0
  flutter_local_notifications: ^9.3.2
  firebase_core: ^1.10.0
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  intl: ^0.17.0
  url_launcher: ^6.0.20
  flutter_phone_direct_caller: ^2.1.1
  flutter_dialpad: ^1.0.4
  share_plus: ^4.0.4
  badges: ^2.0.2
  image_picker: ^0.8.5+3
  material_design_icons_flutter: ^5.0.6595
  contacts_service: ^0.6.3
  permission_handler: ^10.0.0
  horizontal_data_table: ^4.1.1+1
  get: ^4.6.5
  animated_text_kit: ^4.2.2
  multi_select_flutter: ^4.1.2
  dropdown_textfield: ^1.0.5
  awesome_dialog: ^3.0.2
  autocomplete_textfield: ^2.0.1
  flutter_typeahead: ^4.1.1
  font_awesome_flutter: ^10.2.1
  ribbon_widget: ^1.0.5
  rotated_corner_decoration: ^2.0.0
  duration_button: ^1.0.0
  rating: ^1.0.0-dev.1
  flutter_rating_bar: ^4.0.1
  im_stepper: ^1.0.1+1
  flutter_timeline: ^0.3.0
  pdf: ^3.8.4
  printing: ^5.9.3
  sqflite: ^2.0.3+1
  path: ^1.8.1
  fvm: ^2.4.1
  neopop: ^1.0.2



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  change_app_package_name: ^1.1.0


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/
     - assets/icons/
     - assets/images/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
